### ISSUE TITLE
The L2 Norm Loss

### ISSUE THREAD

**Issue by kjgfcdb** [lancopku/Autoencoder-Matching-Model#2]
It seems that there is a L2_norm loss term(J3) in the total loss according to you paper "An Auto-Encoder Matching Model for Learning Utterance-Level Semantic Dependency in Dialogue Generation". But I didn't find it in the code. Is it because that ignoring it does **not** hurt the performance?

**Comment by Luolc** [comment]
Hi kjgfcdb, 

Sorry for the inconsistency. This code base is an early version of the model instead of the final version presented in the paper. Since the original implementation was based on an outdated public code base which had many bugs, I had planned to refactor the code with ParlAI lib (based on PyTorch), therefore I did not choose to fix this issue in current codes but directly in new codes.

But unfortunately, the refactoring is slow as I also have many other works to handle. :(

The L2 loss does not much influence the performance and the end-to-end loss plays a more important role according to our experiments. (that's another reason why I leave it as-is ...) You may get a slightly worse result w/o the L2 loss. If you need to use the final model, you can manually add a loss to the total loss by your self as a workaround.

**Comment by kjgfcdb** [comment]
Thank you for your reply.
